### PR TITLE
Racing Trials Mechanic

### PR DESCRIPTION
**Pull request by KristineSaroka**
add simple route system into game which has an established communication between the race and time trial events

### CODE REVIEW

**Comment by KristineSaroka** [comment]
Best course of action to avoid any damage to the master branch, would be to remove any and all modification

**Comment by KristineSaroka** [comment]
When merging, this branch's scene will be disposed off whilst keeping the master branch's scene as it was.
This branch has only added the race and time trial manager prefabs into the Environment scene for ease of testing
These prefabs exist within the Mechanics section of the prefabs directory

**Comment by DkITJamesFarrell** [comment]
Hey Kristine, I think I know a way that we can resolve some of these merge conflicts. Maybe we should hop on a call this morning?

**Review by DkITJamesFarrell — CHANGES_REQUESTED** [review]
Pull requests should be named according to the CONTRIBUTING.md guidelines - check out the creating pull requests section!

**Review by KristineSaroka — COMMENTED** [review]
Okay

**Pull request merged**
